### ISSUE TITLE
Please use a different icon

### ISSUE THREAD

**Issue by Nightfirecat** [allenkinzalow/npc-spawns#1]
The dev tools icon is generally confusing to encounter while we provide support in the discord, particularly for a legitimate hub plugin. Please use some other icon.

**Comment by Nightfirecat** [comment]
This plugin has been disabled on the hub in <https://github.com/runelite/plugin-hub/commit/976c7ff4264bf948b867b7a817d6862e9e8936cb>. Please follow up on this issue for it to be re-enabled.

**Comment by mdtoupin** [comment]
@allenkinzalow I use this all the time. Made one for you -> https://i.imgur.com/yNifqGC.png

**Comment by allenkinzalow** [comment]
> @allenkinzalow I use this all the time. Made one for you -> https://i.imgur.com/yNifqGC.png

I did not realize the plugin was still used by others that often. I'll get it updated 👍

**Comment by allenkinzalow** [comment]
PR submitted: https://github.com/runelite/plugin-hub/pull/2083

**Comment by Nightfirecat** [comment]
Thanks!
